server:
  port: 8801
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: com.bambi.springcloud.vo
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: springCloud-demoAtSchool-provider
  datasource:
    #设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud01?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Reindeer

#配置eureka的配置 配置服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/,http://localhost:7002/eureka/
  instance:
    #修改eureka上的默认描述信息
    instance-id: springcloud-demoAtSchool-provider-8001
    prefer-ip-address: true
