#编写配置文件
server:
  port: 8003
mybatis:
  #数据库映射类的位置
  type-aliases-package: com.bambi.springcloud.api.vo
  #mapper的位置
  mapper-locations: classpath:mybatis/mapper/*.xml
  #mybatis的核心配置文件
  #config-location: classpath:mybatis/mybatis-config.xml
#大小写转换，将驼峰命名转为数据库命名
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: springCloud-provider-dept
  datasource:
    #设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddb03?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Reindeer

#配置eureka的配置 配置服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/,http://eureka7002.com:7002/eureka/,http://eureka7003.com:7003/eureka/
  instance:
    #修改eureka上的默认描述信息
    instance-id: springcloud-provider-dept-8003
    prefer-ip-address: true

#填写监控信息
info:
  app.name: bambi