server:
  port: 8801
mybatis:
  type-aliases-package: com.bambi.demo.springcloud.vo
  mapper-locations: classpath:mybatis/mapper/*.xml

  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: springcloud-demo-provider-01
  datasource:
    #设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddb02?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Reindeer

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: springcloud-demo-provider-01
    prefer-ip-address: true

info:
  app.name: bambi's provider