server:
  port: 8001
mybatis:
  type-aliases-package: com.bambi.spring.api.pojo
  mapper-locations: classpaths:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

spring:
  application:
    name: springCloud-provider-dept-8001
  datasource:
    #设置数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springcloud01?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true&allowPublicKeyRetrieval=true
    username: root
    password: Reindeer
