server:
  port: 7003

#Eureka配置
eureka:
  instance:
    #实例化主机的名字，告诉主机你是谁
    #服务端的实例名称
    hostname: bambiEureka7003
  client:
    #表示是否向eureka注册中心注册自己  (如果不是集群就不用)
    register-with-eureka: false
    #如果为false 则表示自己为注册中心  维护这些实例，不需要检索这些服务，等待别人连接
    fetch-registry: false
    service-url:
      #取到自己的主机名，端口号
      #必须进行动态配置，不然就需要进入规定的网址访问
      #监控页面
      defaultZone: http://bambiEureka7002:7002/eureka/,http://bambiEureka7001:7001/eureka/